name: LocaleLib
main: me.pikamug.localelib.LocaleLib
version: 2.0
api-version: 1.13
description: Show translated names of items, entities & more in client's language
website: https://www.spigotmc.org/resources/quests.3711/
dev-url: https://github.com/PikaMug/LocaleLib
author: PikaMug
